repos:
  - repo: https://github.com/psf/black
    rev: stable # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3.7 # Should be a command that runs python3.6+
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black"]
